version: "3.8"

services:
  stock_analisys_react:
    working_dir: /var/www/html/localhost/stock-analisis-react/
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./src:/var/www/html/localhost/stock-analisis-react/src
    stdin_open: true
    tty: true
